import Head from "next/head";
import Image from "next/image";
import { checkout } from "@/checkout";
export default function Home() {
  const ronaldoImage =
    "https://static01.nyt.com/images/2022/12/30/multimedia/30soccer-ronaldo-1-76fd/30soccer-ronaldo-1-76fd-articleLarge.jpg?quality=75&auto=webp&disable=upscale";
  const messiImage =
    "https://assets.goal.com/v3/assets/bltcc7a7ffd2fbf71f5/blt12dbddde5342ce4c/648866ff21a8556da61fa167/GOAL_-_Blank_WEB_-_Facebook_-_2023-06-13T135350.847.png?auto=webp&format=pjpg&width=3840&quality=60";
  return (
    <>
      <Head>
        <title>Physical NFTs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Buy my phsical NFTs</h1>
      <div className="boxes">
        <div className="box">
          <img src={ronaldoImage} width={200} height={200}></img>
          <p>Penaldo now for sale. Don't even bother to buy that loser.</p>
          <button
            onClick={() => {
              checkout({
                lineItems: [
                  {
                    price: "price_1NTVe5IbC1SyYwhmkz4rhAa6",
                    quantity: 1,
                  },
                ],
              });
            }}
          >
            BUY!
          </button>
        </div>
        <div className="box">
          <img src={messiImage} width={200} height={200}></img>
          <p>What color is your World Cup? Gold...</p>
        </div>
      </div>
    </>
  );
}
